# Generated by Django 2.1.7 on 2019-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, max_length=255)),
                ('lng', models.FloatField(blank=True, max_length=255)),
            ],
        ),
    ]
