# Generated by Django 2.1.7 on 2019-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='lng',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
